sudo: required

language: python

services:
- docker

before_install:
- docker pull srault95/python-installer
- docker version

script:
- docker run --rm -v $PWD:/app srault95/python-installer /app/build-fabric.sh
- ./dist/fabric-py27-x86-64 --version

before_deploy:
- git config --local user.name "srault95"
- git config --local user.email "stephane.rault@radicalspam.org"
- git tag "$(head -1 version)"

deploy:
  provider: releases
  api_key:
    secure: KbPy8h2PHEtrn47LM8v5D2uncgRkPWw84iheDZG4eMPdbr95L0RZmjkIRvbKDbf0yCYwlywdttjLuRS9cGSDpTNbD7cXQtZut3HfYm9j9vTOEopDOmZVdFi+TVwajoOM0cmKro7qyvKmsiHteqgARXG+i1Xg9NPilCwTjdnGfAldt9xhnGUVJtodLFd7D+QE1v2M7xL6AP3XW4KekU6G8bV+Re0TlcJ1b8QCMjaWY6+WOoQPWytbZ3upKTpzllzTSafiRZxmN4wUgBNVkofr2PCj7rNgvKLbSJ3FII4FjYt7Y8szghYsvQ7lcvh7yYB2zpgDnJL4XvukA348b/OzOG+zqSZaNepcce35JmhbV6xpqYSIt4Cw+AWENoGPb1II0w2flimqOEllkHXo4WMI+l0HLSVLUaCH8tFqqYFwcS4SUweUA5faeNGaJ2mB9JfjLEiIzwZAl8QhK1dtrj+AUYnM58j9QAqMWiqbnYkyUSeYb3fx3ahGdbRTLhjMRPBO8DV7mZCoKav6nlno+4VKVPrhxbzPEyZ1yJ/+A2TF+MG7EQJjDWMXTzc/bwm2LCy6BC8BM/YCRW7AsVq/6Zk+zUAvB915tGU0f6eX9XqxE2/zRqesaUOyC1qaaeXRvlVMVg9XGV2giIWvUW4K3s3w4CEOpzG4VgDVlKwIHCzcgIU=
  file: dist/fabric-py27-x86-64
  skip_cleanup: true
  on:
    branch: master